# Generated by Django 4.0.3 on 2022-04-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_editor',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
