# Generated by Django 4.0.3 on 2022-04-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_initial'),
        ('main_pg', '0009_alter_song_name_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_editor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.artist'),
        ),
    ]
