# Generated by Django 4.0.3 on 2022-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0015_alter_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.FileField(default=None, upload_to='media/albums'),
        ),
    ]
