# Generated by Django 4.0.3 on 2022-04-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0016_album_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='songs',
        ),
    ]
