# Generated by Django 4.0.3 on 2022-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0020_remove_user_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
    ]
