# Generated by Django 4.0.3 on 2022-05-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0022_remove_user_profile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='instagram_link',
            new_name='first_link',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='telegram_link',
            new_name='second_link',
        ),
    ]
