# Generated by Django 4.0.3 on 2022-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0024_alter_user_profile_first_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='first_link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='second_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
