# Generated by Django 4.0.3 on 2022-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0025_user_profile_email_alter_user_profile_first_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_photo',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
    ]
