# Generated by Django 4.0.3 on 2022-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0026_user_profile_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_photo',
            field=models.ImageField(default=None, null=True, upload_to='media/images'),
        ),
    ]
