# Generated by Django 4.0.3 on 2022-05-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0028_remove_user_profile_user_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_posts',
        ),
    ]
