# Generated by Django 4.0.3 on 2022-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0030_user_wall_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_wall_post',
            name='date_of_post',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
