# Generated by Django 4.0.3 on 2022-05-30 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_pg', '0032_main_page_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_page_Posts',
            new_name='Main_page_Post',
        ),
    ]
