# Generated by Django 4.0.3 on 2022-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0033_rename_main_page_posts_main_page_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='name_song',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='name_album',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
