# Generated by Django 4.0.3 on 2022-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0034_rename_album_album_song_album_name_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_song',
        ),
        migrations.AlterField(
            model_name='album',
            name='name_album',
            field=models.CharField(max_length=100),
        ),
    ]
