# Generated by Django 4.0.3 on 2022-06-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0037_rename_album_album_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='songs',
            new_name='song',
        ),
    ]
