# Generated by Django 4.0.3 on 2022-06-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0038_rename_songs_album_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='name_song',
        ),
    ]
