# Generated by Django 4.0.3 on 2022-06-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0044_rename_song_album_album_remove_album_name_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='song',
        ),
    ]
