# Generated by Django 4.0.3 on 2022-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0045_rename_album_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name_song',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
