# Generated by Django 4.0.3 on 2022-04-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_editor',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
