# Generated by Django 4.0.3 on 2022-04-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pg', '0011_alter_album_album_editor_alter_song_song_editor'),
        ('registration', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
