version: "3.8.10"

services:

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/mus_cloud
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=course
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db


  '''image: postgres
  volumes:
    - ./data/db:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=course
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=course
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db'''